### PR TITLE
Adding support for TrailDB filters

### PR DESCRIPTION
**Pull request by KalenAnson**
This commit allows the use of filters. I will update the README to illustrate filter usage.

### CODE REVIEW

**Comment by charlesfeng** [comment]
Hey @KalenAnson, this is awesome!! One minute detail -- there are some inconsistencies with tabs and spaces; could you use 2x spaces instead of tabs to keep the files consistent? Thanks :)

**Comment by KalenAnson** [comment]
Done. :)

Added some boilerplate in the README as well. Feel free to change that if it is not helpful or clear.

**Comment by KalenAnson** [comment]
Really appreciate the work on this library BTW. Hugely helpful in getting my TDB viewer off the ground!

**Comment by charlesfeng** [comment]
That was fast! Thanks again, and amazing work :)

**Pull request merged**
